package org.protege.ontoviz;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author musax
 */
public class OntoVizGUI extends javax.swing.JFrame {

   /**
    * Creates new form OntoVizGUI
    */
   public OntoVizGUI() {
      initComponents();
      layoutCtrlPanel.setVisible(false);
      arcTypeCtrlPanel.setVisible(false);
      nodeTypeCtrlPanel.setVisible(false);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">


   private void initComponents() {

      jPanel6 = new javax.swing.JPanel();
      jPanel1 = new javax.swing.JPanel();
      infoPanel = new javax.swing.JPanel();
      jPanel3 = new javax.swing.JPanel();
      jToggleButton1 = new javax.swing.JToggleButton("+");
      jLabel4 = new javax.swing.JLabel();
      layoutCtrlPanel = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jPanel4 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      jToggleButton2 = new javax.swing.JToggleButton("+");
      arcTypeCtrlPanel = new javax.swing.JPanel();
      checkbox1 = new java.awt.Checkbox();
      checkbox2 = new java.awt.Checkbox();
      checkbox3 = new java.awt.Checkbox();
      jPanel5 = new javax.swing.JPanel();
      jLabel6 = new javax.swing.JLabel();
      jToggleButton3 = new javax.swing.JToggleButton("+");
      nodeTypeCtrlPanel = new javax.swing.JPanel();
      checkbox4 = new java.awt.Checkbox();
      checkbox5 = new java.awt.Checkbox();







      javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
      jPanel6.setLayout(jPanel6Layout);
      jPanel6Layout.setHorizontalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
         );
      jPanel6Layout.setVerticalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
         );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      infoPanel.setBackground(new java.awt.Color(153, 204, 255));
      infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      infoPanel.setMaximumSize(new java.awt.Dimension(402, 546));
      infoPanel.setMinimumSize(new java.awt.Dimension(402, 546));
      infoPanel.setName(""); // NOI18N

      jPanel3.setBackground(new java.awt.Color(51, 153, 255));

      jToggleButton1.addItemListener(
         new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
               jToggleButton1ItemStateChanged(evt);
            }
         });

      OntoVizConstants.setUpLabel(jLabel4, "Layout");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
             .addContainerGap()
             .addComponent(jToggleButton1)
             .addGap(94, 94, 94)
             .addComponent(jLabel4)
             .addContainerGap(129, Short.MAX_VALUE))
         );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
             .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
         );

      layoutCtrlPanel.setBackground(new java.awt.Color(153, 204, 255));


      OntoVizConstants.setUpButton(jButton1, OntoVizIcons.GRID, "Grid","");

      OntoVizConstants.setUpButton(jButton2, OntoVizIcons.VERT, "Vertical","");

      OntoVizConstants.setUpButton(jButton3, OntoVizIcons.RAD, "Radial","");

      OntoVizConstants.setUpButton(jButton5, OntoVizIcons.HORI, "Horizontal","");

      javax.swing.GroupLayout layoutCtrlPanelLayout = new javax.swing.GroupLayout(layoutCtrlPanel);
      layoutCtrlPanel.setLayout(layoutCtrlPanelLayout);
      layoutCtrlPanelLayout.setHorizontalGroup(
         layoutCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layoutCtrlPanelLayout.createSequentialGroup()
             .addGap(24, 24, 24)
             .addGroup(layoutCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                 .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGap(54, 54, 54)
             .addGroup(layoutCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addComponent(jButton5))
             .addContainerGap(51, Short.MAX_VALUE))
         );
      layoutCtrlPanelLayout.setVerticalGroup(
         layoutCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layoutCtrlPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(layoutCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(jButton1)
                 .addComponent(jButton3))
             .addGap(15, 15, 15)
             .addGroup(layoutCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(jButton2)
                 .addComponent(jButton5))
             .addContainerGap())
         );

      jPanel4.setBackground(new java.awt.Color(51, 153, 255));

      OntoVizConstants.setUpLabel(jLabel5, "Node Types");

      jToggleButton2.addItemListener(
         new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
               jToggleButton2ItemStateChanged(evt);
            }
         });

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
             .addContainerGap()
             .addComponent(jToggleButton2)
             .addGap(77, 77, 77)
             .addComponent(jLabel5)
             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
             .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
             .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
         );

      arcTypeCtrlPanel.setBackground(new java.awt.Color(153, 204, 255));
      arcTypeCtrlPanel.setPreferredSize(new java.awt.Dimension(136, 106));

      checkbox1.setLabel("arc type item 1");

      checkbox2.setLabel("arc type item 2");

      checkbox3.setLabel("arc type item 3");

      javax.swing.GroupLayout arcTypeCtrlPanelLayout = new javax.swing.GroupLayout(arcTypeCtrlPanel);
      arcTypeCtrlPanel.setLayout(arcTypeCtrlPanelLayout);
      arcTypeCtrlPanelLayout.setHorizontalGroup(
         arcTypeCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arcTypeCtrlPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(arcTypeCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                 .addComponent(checkbox3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                 .addComponent(checkbox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(checkbox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addContainerGap())
         );
      arcTypeCtrlPanelLayout.setVerticalGroup(
         arcTypeCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(arcTypeCtrlPanelLayout.createSequentialGroup()
             .addGap(18, 18, 18)
             .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(2, 2, 2)
             .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(2, 2, 2)
             .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );

      jPanel5.setBackground(new java.awt.Color(51, 153, 255));

      OntoVizConstants.setUpLabel(jLabel6, "Arc Types");

      jToggleButton3.addItemListener(
         new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
               jToggleButton3ItemStateChanged(evt);
            }
         });

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
             .addContainerGap()
             .addComponent(jToggleButton3)
             .addGap(80, 80, 80)
             .addComponent(jLabel6)
             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
             .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
             .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
         );

      nodeTypeCtrlPanel.setBackground(new java.awt.Color(153, 204, 255));

      checkbox4.setLabel("node type item 1");

      checkbox5.setLabel("node type item 2");

      javax.swing.GroupLayout nodeTypeCtrlPanelLayout = new javax.swing.GroupLayout(nodeTypeCtrlPanel);
      nodeTypeCtrlPanel.setLayout(nodeTypeCtrlPanelLayout);
      nodeTypeCtrlPanelLayout.setHorizontalGroup(
         nodeTypeCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nodeTypeCtrlPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(nodeTypeCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(checkbox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(checkbox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addContainerGap())
         );
      nodeTypeCtrlPanelLayout.setVerticalGroup(
         nodeTypeCtrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(nodeTypeCtrlPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(checkbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(2, 2, 2)
             .addComponent(checkbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addContainerGap(54, Short.MAX_VALUE))
         );

      javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
      infoPanel.setLayout(infoPanelLayout);
      infoPanelLayout.setHorizontalGroup(
         infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(nodeTypeCtrlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(arcTypeCtrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         .addComponent(layoutCtrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         );
      infoPanelLayout.setVerticalGroup(
         infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(infoPanelLayout.createSequentialGroup()
             .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(layoutCtrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(nodeTypeCtrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
             .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(arcTypeCtrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addContainerGap(121, Short.MAX_VALUE))
         );

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
             .addGap(0, 528, Short.MAX_VALUE)
             .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         );








      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
             .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         );

      pack();
   }// </editor-fold>

   private void jToggleButton1ItemStateChanged(ItemEvent evt) {
      OntoVizConstants.toggleEvt(evt, jToggleButton1, layoutCtrlPanel);
   }

   private void jToggleButton2ItemStateChanged(ItemEvent evt) {
      OntoVizConstants.toggleEvt(evt, jToggleButton2, nodeTypeCtrlPanel);
   }

   private void jToggleButton3ItemStateChanged(ItemEvent evt) {
      OntoVizConstants.toggleEvt(evt, jToggleButton3, arcTypeCtrlPanel);
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(OntoVizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(OntoVizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(OntoVizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(OntoVizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(
         new Runnable() {
            public void run() {
               new OntoVizGUI().setVisible(true);
            }
         });
   }




   // Variables declaration - do not modify
   private javax.swing.JPanel arcTypeCtrlPanel;
   private java.awt.Checkbox checkbox1;
   private java.awt.Checkbox checkbox2;
   private java.awt.Checkbox checkbox3;
   private java.awt.Checkbox checkbox4;
   private java.awt.Checkbox checkbox5;
   private javax.swing.JPanel infoPanel;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton5;

   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel topPanel;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JToggleButton jToggleButton1;
   private javax.swing.JToggleButton jToggleButton2;
   private javax.swing.JToggleButton jToggleButton3;
   private javax.swing.JPanel layoutCtrlPanel;
   private javax.swing.JPanel nodeTypeCtrlPanel;

   // End of variables declaration
}
